-- MySQL Script generated by MySQL Workbench
-- 09/10/18 14:48:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lembreteDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lembreteDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS lembreteDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE lembreteDB ;

-- -----------------------------------------------------
-- Table lembreteDB.Lembrete
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS lembreteDB.Lembrete (
  id INT NOT NULL AUTO_INCREMENT,
  data DATETIME NOT NULL,
  Descricao VARCHAR(200) NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
